//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/BreakingDown/Scripts/InputStuff/Movement.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Movement: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Movement()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Movement"",
    ""maps"": [
        {
            ""name"": ""PlayerMain"",
            ""id"": ""4e0fabc1-3ced-43b0-90b1-8972f0391212"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""7280aa05-59d2-4f93-95f5-3687f4c25ed4"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""LookAround"",
                    ""type"": ""Value"",
                    ""id"": ""ca123cc9-9524-44c7-bd47-2e3862624a26"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""b42f2cf2-6141-42e3-aa98-69abe277bea7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GrabThrow"",
                    ""type"": ""Button"",
                    ""id"": ""a083ea5a-25ca-4d81-827b-a291441f15b8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BasicCombo"",
                    ""type"": ""Button"",
                    ""id"": ""c57c0da0-24f9-4f28-b389-1b8e089fa5a5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BasicCombo2"",
                    ""type"": ""Button"",
                    ""id"": ""68658a9a-628c-4415-acc8-5794fdf7ba95"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpeicalCombo"",
                    ""type"": ""Button"",
                    ""id"": ""48984545-d45b-4a85-976b-9fe863dc1b1c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Throw"",
                    ""type"": ""Button"",
                    ""id"": ""5ea458f1-e06e-45e8-b672-edc5da8e3135"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ThrowEscape"",
                    ""type"": ""Button"",
                    ""id"": ""27f37f92-44f7-428d-92a9-e98b2fac95af"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CameraLock"",
                    ""type"": ""Button"",
                    ""id"": ""b0221a4d-0db2-441f-8563-815018092181"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Block"",
                    ""type"": ""Button"",
                    ""id"": ""8a42b363-56db-4956-99c6-4bf2926a699f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Hold"",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""46dc23b1-8b45-4cf9-b359-d8b3f2b1260b"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""5a1f1099-9a8c-4ac2-8b38-8321124e69a8"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""bd4ddbe9-4b88-4ed4-b5bb-aebf638605ba"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""3c57b719-a1bd-48d4-a0e0-a3949d50ab18"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""99413ce2-d35b-4e5e-bf42-1fa53f05c2f9"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""4008638e-c454-40b3-90d9-feed3bac0c77"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""566b521e-04c5-44aa-a769-f19f00c1b652"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LookAround"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7f37ab75-9b05-4018-9114-f4230d3e4e81"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6193b1f7-b808-419d-ad0b-7993bf2707c4"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GrabThrow"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""96989e97-88a2-424d-a275-31751db0cb04"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BasicCombo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e5178ed7-71c9-4032-a6aa-4478f74f6622"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpeicalCombo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c5726edc-2bc7-4e94-ac68-37aa79191ed7"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Throw"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7f3e9e88-4489-4b3a-a261-97ad2cebd936"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThrowEscape"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c813ba00-c816-4f10-a9b2-826fc971d1ed"",
                    ""path"": ""<Keyboard>/v"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BasicCombo2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""96338d8c-fc1e-4750-9c15-95ff8d0e0bdd"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraLock"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""008f93d4-152d-4604-a1c2-e6ef854cda9b"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Block"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerMain
        m_PlayerMain = asset.FindActionMap("PlayerMain", throwIfNotFound: true);
        m_PlayerMain_Move = m_PlayerMain.FindAction("Move", throwIfNotFound: true);
        m_PlayerMain_LookAround = m_PlayerMain.FindAction("LookAround", throwIfNotFound: true);
        m_PlayerMain_Jump = m_PlayerMain.FindAction("Jump", throwIfNotFound: true);
        m_PlayerMain_GrabThrow = m_PlayerMain.FindAction("GrabThrow", throwIfNotFound: true);
        m_PlayerMain_BasicCombo = m_PlayerMain.FindAction("BasicCombo", throwIfNotFound: true);
        m_PlayerMain_BasicCombo2 = m_PlayerMain.FindAction("BasicCombo2", throwIfNotFound: true);
        m_PlayerMain_SpeicalCombo = m_PlayerMain.FindAction("SpeicalCombo", throwIfNotFound: true);
        m_PlayerMain_Throw = m_PlayerMain.FindAction("Throw", throwIfNotFound: true);
        m_PlayerMain_ThrowEscape = m_PlayerMain.FindAction("ThrowEscape", throwIfNotFound: true);
        m_PlayerMain_CameraLock = m_PlayerMain.FindAction("CameraLock", throwIfNotFound: true);
        m_PlayerMain_Block = m_PlayerMain.FindAction("Block", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerMain
    private readonly InputActionMap m_PlayerMain;
    private List<IPlayerMainActions> m_PlayerMainActionsCallbackInterfaces = new List<IPlayerMainActions>();
    private readonly InputAction m_PlayerMain_Move;
    private readonly InputAction m_PlayerMain_LookAround;
    private readonly InputAction m_PlayerMain_Jump;
    private readonly InputAction m_PlayerMain_GrabThrow;
    private readonly InputAction m_PlayerMain_BasicCombo;
    private readonly InputAction m_PlayerMain_BasicCombo2;
    private readonly InputAction m_PlayerMain_SpeicalCombo;
    private readonly InputAction m_PlayerMain_Throw;
    private readonly InputAction m_PlayerMain_ThrowEscape;
    private readonly InputAction m_PlayerMain_CameraLock;
    private readonly InputAction m_PlayerMain_Block;
    public struct PlayerMainActions
    {
        private @Movement m_Wrapper;
        public PlayerMainActions(@Movement wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_PlayerMain_Move;
        public InputAction @LookAround => m_Wrapper.m_PlayerMain_LookAround;
        public InputAction @Jump => m_Wrapper.m_PlayerMain_Jump;
        public InputAction @GrabThrow => m_Wrapper.m_PlayerMain_GrabThrow;
        public InputAction @BasicCombo => m_Wrapper.m_PlayerMain_BasicCombo;
        public InputAction @BasicCombo2 => m_Wrapper.m_PlayerMain_BasicCombo2;
        public InputAction @SpeicalCombo => m_Wrapper.m_PlayerMain_SpeicalCombo;
        public InputAction @Throw => m_Wrapper.m_PlayerMain_Throw;
        public InputAction @ThrowEscape => m_Wrapper.m_PlayerMain_ThrowEscape;
        public InputAction @CameraLock => m_Wrapper.m_PlayerMain_CameraLock;
        public InputAction @Block => m_Wrapper.m_PlayerMain_Block;
        public InputActionMap Get() { return m_Wrapper.m_PlayerMain; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerMainActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerMainActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerMainActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerMainActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @LookAround.started += instance.OnLookAround;
            @LookAround.performed += instance.OnLookAround;
            @LookAround.canceled += instance.OnLookAround;
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
            @GrabThrow.started += instance.OnGrabThrow;
            @GrabThrow.performed += instance.OnGrabThrow;
            @GrabThrow.canceled += instance.OnGrabThrow;
            @BasicCombo.started += instance.OnBasicCombo;
            @BasicCombo.performed += instance.OnBasicCombo;
            @BasicCombo.canceled += instance.OnBasicCombo;
            @BasicCombo2.started += instance.OnBasicCombo2;
            @BasicCombo2.performed += instance.OnBasicCombo2;
            @BasicCombo2.canceled += instance.OnBasicCombo2;
            @SpeicalCombo.started += instance.OnSpeicalCombo;
            @SpeicalCombo.performed += instance.OnSpeicalCombo;
            @SpeicalCombo.canceled += instance.OnSpeicalCombo;
            @Throw.started += instance.OnThrow;
            @Throw.performed += instance.OnThrow;
            @Throw.canceled += instance.OnThrow;
            @ThrowEscape.started += instance.OnThrowEscape;
            @ThrowEscape.performed += instance.OnThrowEscape;
            @ThrowEscape.canceled += instance.OnThrowEscape;
            @CameraLock.started += instance.OnCameraLock;
            @CameraLock.performed += instance.OnCameraLock;
            @CameraLock.canceled += instance.OnCameraLock;
            @Block.started += instance.OnBlock;
            @Block.performed += instance.OnBlock;
            @Block.canceled += instance.OnBlock;
        }

        private void UnregisterCallbacks(IPlayerMainActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @LookAround.started -= instance.OnLookAround;
            @LookAround.performed -= instance.OnLookAround;
            @LookAround.canceled -= instance.OnLookAround;
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
            @GrabThrow.started -= instance.OnGrabThrow;
            @GrabThrow.performed -= instance.OnGrabThrow;
            @GrabThrow.canceled -= instance.OnGrabThrow;
            @BasicCombo.started -= instance.OnBasicCombo;
            @BasicCombo.performed -= instance.OnBasicCombo;
            @BasicCombo.canceled -= instance.OnBasicCombo;
            @BasicCombo2.started -= instance.OnBasicCombo2;
            @BasicCombo2.performed -= instance.OnBasicCombo2;
            @BasicCombo2.canceled -= instance.OnBasicCombo2;
            @SpeicalCombo.started -= instance.OnSpeicalCombo;
            @SpeicalCombo.performed -= instance.OnSpeicalCombo;
            @SpeicalCombo.canceled -= instance.OnSpeicalCombo;
            @Throw.started -= instance.OnThrow;
            @Throw.performed -= instance.OnThrow;
            @Throw.canceled -= instance.OnThrow;
            @ThrowEscape.started -= instance.OnThrowEscape;
            @ThrowEscape.performed -= instance.OnThrowEscape;
            @ThrowEscape.canceled -= instance.OnThrowEscape;
            @CameraLock.started -= instance.OnCameraLock;
            @CameraLock.performed -= instance.OnCameraLock;
            @CameraLock.canceled -= instance.OnCameraLock;
            @Block.started -= instance.OnBlock;
            @Block.performed -= instance.OnBlock;
            @Block.canceled -= instance.OnBlock;
        }

        public void RemoveCallbacks(IPlayerMainActions instance)
        {
            if (m_Wrapper.m_PlayerMainActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerMainActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerMainActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerMainActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerMainActions @PlayerMain => new PlayerMainActions(this);
    public interface IPlayerMainActions
    {
        void OnMove(InputAction.CallbackContext context);
        void OnLookAround(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnGrabThrow(InputAction.CallbackContext context);
        void OnBasicCombo(InputAction.CallbackContext context);
        void OnBasicCombo2(InputAction.CallbackContext context);
        void OnSpeicalCombo(InputAction.CallbackContext context);
        void OnThrow(InputAction.CallbackContext context);
        void OnThrowEscape(InputAction.CallbackContext context);
        void OnCameraLock(InputAction.CallbackContext context);
        void OnBlock(InputAction.CallbackContext context);
    }
}
